spring.application.name=learn_spring
spring.main.banner-mode=off
logging.level.com.pet.learn_spring=DEBUG
logging.level.org.springframework=ERROR

com.custom-value.trees=100
com.custom-value.filesystem-minimum-free-disk-space=1000000
com.custom-value.filesystem-low-free-disk-space=10
spring.main.lazy-initialization=true

com.custom-value.servers[0].ip=126.32.66.28
com.custom-value.servers[1].ip=111.229.178.175

com.custom-value.server-map.home-server.ip=126.32.66.28
com.custom-value.server-map.traffic-server.ip=111.229.178.175