spring.application.name=learn_spring
spring.main.banner-mode=off
logging.level.com.pet.learn_spring=DEBUG
logging.level.org.springframework=ERROR

com.custom-value.trees=100
com.custom-value.filesystem-minimum-free-disk-space=1000000
spring.main.lazy-initialization=true